### PR TITLE
Problem: HellOS doesn't compile on Zig 0.8.0

### PR DESCRIPTION
**Pull request by yrashk**
Solution: update API usage

### CODE REVIEW

**Comment by Omega0x013** [comment]
I have this problem too, but I changed
`const builtin = @import("builtin");`
to
`const builtin = @import("std").builtin;`

**Comment by sagehane** [comment]
Side note: running `zig ast-check` on the latest Zig (0.9.0-pre) gives me the following message:
```zig
$ zig ast-check hellos.zig
hellos.zig:29:31: error: unused function parameter
pub fn panic(msg: []const u8, error_return_trace: ?*std.builtin.StackTrace) noreturn {
```
Why is the `error_return_trace` even necessary?
